plugins {
    id 'net.fabricmc.fabric-loom' version "${loom_version}"
    id 'maven-publish'
    id 'com.diffplug.spotless' version "${spotless_version}"
}

version = "${project.mod_version}"
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

loom {
    runs {
        client {
            property "devauth.enabled", "true"
            property "devauth.account", "main"
        }
    }
}

repositories {
    maven { url = "https://maven.fabricmc.net/" }
    maven { url = "https://maven.shedaniel.me" }
    maven { url = "https://maven.teamresourceful.com/repository/maven-public/" }
    maven { url = "https://pkgs.dev.azure.com/djtheredstoner/DevAuth/_packaging/public/maven/v1" }
    maven { url = "https://repo.hypixel.net/repository/Hypixel/" }
    maven { url = "https://maven.terraformersmc.com/releases" }
    maven { url = "https://api.modrinth.com/maven" }
    gradlePluginPortal()
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"

    // Fabric
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}+${project.minecraft_version}"
    implementation "net.fabricmc:fabric-language-kotlin:${project.fabric_language_kotlin_version}"

    // REI
    compileOnly "me.shedaniel:RoughlyEnoughItems-api-fabric:${project.rei_version}"
    runtimeOnly "me.shedaniel:RoughlyEnoughItems-fabric:${project.rei_version}"
    compileOnly "me.shedaniel:RoughlyEnoughItems-default-plugin-fabric:${project.rei_version}"
    runtimeOnly "me.shedaniel:RoughlyEnoughItems-default-plugin-fabric:${project.rei_version}"
    compileOnly "me.shedaniel.cloth:basic-math:${project.cloth_basic_math_version}"

    // Mod Menu
    compileOnly  "maven.modrinth:modmenu:${project.modmenu_version}"
    localRuntime "maven.modrinth:modmenu:${project.modmenu_version}"

    // Dev Auth
    localRuntime "me.djtheredstoner:DevAuth-fabric:${project.devauth_version}"

    // SkyBlock Api
    api("tech.thatgravyboat:skyblock-api:${project.skyblockapi_version}") {
        capabilities {
            requireCapability("tech.thatgravyboat:skyblock-api-${project.skyblockapi_mc_version}")
        }
    }
    include("tech.thatgravyboat:skyblock-api:${project.skyblockapi_version}") {
        capabilities {
            requireCapability("tech.thatgravyboat:skyblock-api-${project.skyblockapi_mc_version}")
        }
    }

    // Unit tests
    testImplementation "org.junit.jupiter:junit-jupiter:${project.junit_version}"
    testRuntimeOnly "org.junit.platform:junit-platform-launcher"
}

processResources {
    inputs.property "version", project.version
    inputs.property "minecraft_version", project.minecraft_version
    inputs.property "skyblockapi_mc_version", project.skyblockapi_mc_version
    inputs.property "loader_version", project.loader_version
    inputs.property "fabric_version", project.fabric_version
    inputs.property "fabric_language_kotlin_version", project.fabric_language_kotlin_version
    inputs.property "rei_version", project.rei_version
    inputs.property "modmenu_version", project.modmenu_version
    inputs.property "skyblockitemlist_version", project.skyblockitemlist_version
    filteringCharset "UTF-8"

    filesMatching("fabric.mod.json") {
        expand "version": project.version,
                "minecraft_version": project.minecraft_version,
                "skyblockapi_mc_version": project.skyblockapi_mc_version,
                "loader_version": project.loader_version,
                "fabric_version": project.fabric_version,
                "fabric_language_kotlin_version": project.fabric_language_kotlin_version,
                "rei_version": project.rei_version,
                "modmenu_version": project.modmenu_version,
                "skyblockitemlist_version": project.skyblockitemlist_version
    }
}

def targetJavaVersion = 25

tasks.withType(JavaCompile).configureEach {
    it.options.encoding = "UTF-8"
    it.options.release.set(targetJavaVersion)
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
    withSourcesJar()
}

test {
    useJUnitPlatform()
}

jar {
    from("LICENSE.txt") {
        rename { "${it}_${project.archives_base_name}" }
    }
}

publishing {
    publications {
        create("mavenJava", MavenPublication) {
            artifactId = project.archives_base_name
            from components.java
        }
    }
    repositories {
    }
}

spotless {
    java {
        target 'src/*/java/**/*.java'
        importOrder('com.rijz.notenoughcalculator', 'tech.thatgravyboat.skyblockapi', 'net.minecraft', 'com.mojang', 'java', 'javax')
        removeUnusedImports()
        eclipse()
        trimTrailingWhitespace()
        endWithNewline()
    }
}
