# Gradle memory config
org.gradle.jvmargs=-Xmx2G

# Minecraft Properties
minecraft_version=26.1.2

# Fabric Properties
loader_version=0.19.5
fabric_version=0.155.3
loom_version=1.17-SNAPSHOT
fabric_language_kotlin_version=1.14.1+kotlin.2.4.20

# Mod Properties
mod_version=3.0.0
maven_group=com.rijz
archives_base_name=notenoughcalculator

# REI
rei_version=26.1.819
cloth_basic_math_version=0.6.1

# Mod Menu
modmenu_version=18.0.1

# Dev Auth
devauth_version=1.2.2

# SkyBlock API & Item List
skyblockapi_version=4.2.23
skyblockapi_mc_version=26.1
skyblockitemlist_version=0.0.21

# Other
spotless_version=8.10.0
junit_version=6.1.3
